# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e08bdb28bb9b1ffe7d7998c0eb0da443d17cf080146c46f8acb37efd2f4e4aae32a2e3acaf6c2ed1596c01788fa6433c7af685f8e2407ad5bc32fbbabf907eaf

test:
  secret_key_base: 38bfe6c7b329f76c90e8e86d9eaa4ab68199e9d0b5f2331dc4092debd8c205370cb6bd64f41d95da1d0f91c6508a7c47b4e734716b08cc69dc2efe82234bc655

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
